name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

    env:
        REGISTRY: docker.io
      
      jobs:
        build-image:
          runs-on: ubuntu-latest
          permissions:
            packages: write
          steps:
            - uses: actions/checkout@v4
            - name: Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: docker.io/juestnow/livetv
                flavor: latest=true
                tags: |
                  type=ref,event=branch
                  type=ref,event=pr
                  type=semver,pattern={{version}}
      
            - name: Login to dokcer Container Registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ secrets.DOCKER_HUB_USER }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
            - # Add support for more platforms with QEMU (optional)
              # https://github.com/docker/setup-qemu-action
              name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
                
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                platforms: linux/amd64
                file: Dockerfile
                push: true
                tags: 1.1
                labels: ${{ steps.meta.outputs.labels }}